version: '3.7'

services:
  app:
    build: .
    container_name: hengehog-app
    restart: always
    ports:
      - '5000:5000'
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: 'npm run start'
